
abstract class MainScreenState{}
class MainScreenIntialState extends MainScreenState{}
class ChangeHomePageChioce extends MainScreenState{}
class ChangeBottomNavigationBarIndexState extends MainScreenState{}
class ThemChangeState extends MainScreenState{}
class ChangePsswordEyeICon extends MainScreenState{}
class CreateController extends MainScreenState{}
class TextFieldCreated extends MainScreenState{}
class ImagePickerLoad extends MainScreenState{}
class TextHeaderFieldCreated extends MainScreenState{}
class SocialSendMessageSuccess extends MainScreenState{}
class SocialSendMessageError extends MainScreenState{}
class SocailGetMessageSuccessSate extends MainScreenState{}
class LoginSuccess extends MainScreenState{}
class LoginFailed extends MainScreenState{}
class TokenSet extends MainScreenState{}
class SignedUpSuccess extends MainScreenState{}
class SignedUpFailed extends MainScreenState{}
class TransferTo64 extends MainScreenState{}
class KeepValuesFieldUpdated extends MainScreenState{}
class GetUserProfile extends MainScreenState{}
class UpdateImageProfile extends MainScreenState{}
class UpdateBioText extends MainScreenState{}
class UpdateUserFirasLstName extends MainScreenState{}
class updatepassword extends MainScreenState{}
class DisableAndNotDiasbledPassword extends MainScreenState{}
class BadRequestPassword extends MainScreenState{}
class ErrorUpadatingPasssword extends MainScreenState{}
class GetContactList extends MainScreenState{}
class SocialGetMessageSuccessSate2 extends MainScreenState{}
class CheckUrlValid extends MainScreenState{}
class DeletContactSuccessfully extends MainScreenState{}
class DeletContactFailed extends MainScreenState{}
class DeleteFirebaseMyPartOfMessage extends MainScreenState{}
class GetContactProfile extends MainScreenState{}
class AddContactSuccessfully extends MainScreenState{}
class FollowedSuccessfully extends MainScreenState{}
class GetFollowers extends MainScreenState{}
class GetFollowings extends MainScreenState{}
class UnfollowSuccess extends MainScreenState{}
class ChecktheIamfollowing extends MainScreenState{}
class FollowUnfollow extends MainScreenState{}
class PostCreated extends MainScreenState{}
class ChangeBottomModalSheetVisibility extends MainScreenState{}
class ViewDataPost extends MainScreenState{}
class TimePassedAgo extends MainScreenState{}
class PickFile extends MainScreenState{}
class Page0 extends MainScreenState{}
class Page1 extends MainScreenState{}
class ClearProjectStuff extends MainScreenState{}
class LikedSuccess extends MainScreenState{}
class LikedError extends MainScreenState{}
class ULikedSuccess extends MainScreenState{}
class ULikedError extends MainScreenState{}
class CommentCreatedSuccess extends MainScreenState{}
class CommentCreatedFailed extends MainScreenState{}


